// <auto-generated />
using System;
using HomiesAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HomiesAPI.Migrations
{
    [DbContext(typeof(HomiesContext))]
    [Migration("20180722183443_CreateCheckIns")]
    partial class CreateCheckIns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HomiesAPI.Models.CheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("HomieId");

                    b.HasKey("Id");

                    b.HasIndex("HomieId");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("HomiesAPI.Models.Homie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("HasGuest");

                    b.Property<bool>("IsHome");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Homies");
                });

            modelBuilder.Entity("HomiesAPI.Models.CheckIn", b =>
                {
                    b.HasOne("HomiesAPI.Models.Homie", "Homie")
                        .WithMany("CheckIns")
                        .HasForeignKey("HomieId");
                });
#pragma warning restore 612, 618
        }
    }
}
